openapi: 3.0.0
info:
    title: Error Responses
    description: Error responses for the Task Management System
    version: '1.0'
paths: {}

components:

    responses:

        BadRequest:
            description: Bad Request
            content:
                application/json:
                    schema:
                        allOf:
                            -   $ref: '#/components/schemas/ErrorResponseBody'
                        example:
                            timestamp: "2020-01-01T00:00:00Z"
                            status: 400
                            error: "Bad Request"
                            path: "/tasks"

        NotFound:
            description: Resource Not Found
            content:
                application/json:
                    schema:
                        allOf:
                            -   $ref: '#/components/schemas/ErrorResponseBody'
                        example:
                            timestamp: "2020-01-01T00:00:00Z"
                            status: 404
                            error: "Resource Not Found"
                            path: "/tasks/{taskId}"


        InternalServerError:
            description: Internal Server Error
            content:
                application/json:
                    schema:
                        allOf:
                            -   $ref: '#/components/schemas/ErrorResponseBody'
                        example:
                            timestamp: "2020-01-01T00:00:00Z"
                            status: 500
                            error: "Internal Server Error"
                            path: "/tasks"

        Unauthorized:
            description: Unauthorized
            headers:
                WWW-Authenticate:
                    schema:
                        type: string
                    example: 'Bearer realm="TaskManagementSystem"'

        AccessDenied:
            description: Access Denied


    schemas:

        ErrorResponseBody:
            type: object
            required:
                - error
            properties:
                timestamp:
                    type: string
                    format: date-time
                status:
                    type: integer
                    format: int32
                    minimum: 100
                    maximum: 599
                error:
                    type: string
                message:
                    type: string
                path:
                    type: string
                    format: uri
                requestId: {}
                errors:
                    type: array
                    items:
                        type: string
                trace:
                    type: string
